### ISSUE TITLE
Update dependent lisk scripts to test lisk migration on core

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-scripts#60]
These are the child issues to keep track of the progress on the core task https://github.com/LiskHQ/lisk/issues/1861

- [x] Update installLisk.sh to accept a flag that will allow install from local tar  #38 
- [x] Backport changes for installLisk.sh for pre 1.0.0 branch #61
- [x] Update lisk_bridge.sh to accept a flag that will allow install from local tar  #46 
- [x] Update lisk-bridge.sh script to migrate config.json file appropriately and validate #62
- [x] Update the path and filename for config migration script #66
